name: Clone Package

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'With TMATE'
        required: false
        default: false

  repository_dispatch:
    types:
      - AUR/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install \
          git \
          wget

      - name: Clone from Aur
        if: ${{ ! inputs.debug_enabled }}
        shell: bash
        run: |
          if [ ! -d "$(cut -d "/" -f2 <<< ${{ github.repository }})" ];then
            git clone https://aur.archlinux.org/$(cut -d "/" -f2 <<< ${{ github.repository }}).git
          else
            echo "XPTO"
            cd $(find -type f -name PKGBUILD | sed 's/PKGBUILD//')
            git pull
          fi

      - name: Setup TMATE Session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Update github
        run: |
          git config --local user.email "gitbarnabedikartola@gmail.com"
          git config --local user.name "gitbarnabedikartola"
          git add --all
          if [ -n "$(git commit -m "update $(date +%y-%m-%d_%H:%M)" -a | grep "nothing to commit")" ];then exit 0; fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

